Fr 18978
frontegg/frontegg-android-kotlin pull request #96
Opened 2024-12-13 16:48 UTC by alex-minaiev-frontegg

2025-01-20 14:39 UTC, frontegg-david requested changes

2025-01-20 14:39 UTC, frontegg-david commented on android/build.gradle
> +        targetSdk 35
we cannot increment the comile and target sdk

2025-01-21 16:30 UTC, alex-minaiev-frontegg commented on android/build.gradle
> +        targetSdk 35
Done

2025-01-27 17:38 UTC, frontegg-david requested changes
resolve conflict  and changes

2025-01-27 17:38 UTC, frontegg-david commented on android/build.gradle
> +    implementation 'androidx.core:core-ktx:1.13.1'
danger upgrade, let's check how we can stick on 1.7 with the testing scripts

2025-01-27 17:38 UTC, frontegg-david commented on android/src/test/java/com/frontegg/android/BlockCoroutineDispatcher.kt
> +
the is the purpose of this file?

2025-01-27 17:38 UTC, frontegg-david commented on build.gradle
> +    id 'com.android.application' version '8.4.2' apply false
dangerous upgrade, let's try to stick on v7

2025-01-27 17:38 UTC, frontegg-david commented on gradle/wrapper/gradle-wrapper.properties
> +distributionUrl=https\://services.gradle.org/distributions/gradle-8.6-bin.zip
dangerous upgrade, let's try to stick on 8.2

2025-01-28 08:38 UTC, alex-minaiev-frontegg commented on build.gradle
> +    id 'com.android.application' version '8.4.2' apply false
I've changed. But pay attention on warning:
```
WARNING:We recommend using a newer Android Gradle plugin to use compileSdk = 34

This Android Gradle plugin (7.4.2) was tested up to compileSdk = 33

This warning can be suppressed by updating
    android.suppressUnsupportedCompileSdk=35,34
to this project's gradle.properties

The build will continue, but you are strongly encouraged to update your project to
use a newer Android Gradle Plugin that has been tested with compileSdk = 34
```

2025-01-28 08:49 UTC, alex-minaiev-frontegg commented
@frontegg-david, I've resolved the conflicts.

2025-01-28 09:27 UTC, frontegg-david commented on android/build.gradle
> +    implementation 'androidx.core:core-ktx:1.13.1'
let's see which version we have in the latest builds and stick with it.

2025-01-28 09:29 UTC, frontegg-david commented on build.gradle
> +    id 'com.android.application' version '8.4.2' apply false
I have compile errors in react-native when upgraded our AndroidSDK to 8

2025-01-28 19:52 UTC, frontegg-david approved these changes

2025-01-28 20:02 UTC, merged